### ISSUE TITLE
Typing character "@" in "Set recovery e-mail" dialog sends the form

### ISSUE THREAD

**Issue by souliane** [MrStahlfelge/lightblocks#1]
Hi,

this is occuring on the gamejolt.net instance. Entering the "@" character in "Set recovery e-mail" dialog automatically sends the form as if I typed the return key or pressed "OK".

Workaround: I can set the email by writing it first without the "@" character and add it at last.

**Comment by MrStahlfelge** [comment]
Thanks for the first issue. :-)

Yes, I am aware of the problem. It does only happen on the web version, and it might be a problem in libgdx. Will check that.

**Comment by MrStahlfelge** [comment]
Retested. Happens on Windows because Alt-Gr gives keycode 18 which is the same as Alt and the game reacts on Alt. Will fix that for the next version and switch over to Ctrl.
