### ISSUE TITLE
Multiplayer server seems to be offline

### ISSUE THREAD

**Issue by souliane** [MrStahlfelge/lightblocks#12]
On my phone and also on gamejolt's client, I get "No internet connection" although I am actually connected.

**Comment by MrStahlfelge** [comment]
Can confirm, the game's website is also unreachable. The server itself is up and running, looks like the outer http server went down. I reached out to the host admin.

**Comment by MrStahlfelge** [comment]
Apache was restarted and service is back again. :) 
Thanks for the tip!
