### ISSUE TITLE
Hard drop button for on screen buttons

### ISSUE THREAD

**Issue by MrStahlfelge** [MrStahlfelge/lightblocks#16]
Could be shown here

![harddrop](https://user-images.githubusercontent.com/26038055/90983955-31a2b280-e572-11ea-9130-735b4601360c.jpg)

Problem: On iOS, the pause button shown there when in portrait mode.

**Comment by souliane** [comment]
This is something I didn't dare to ask for, but I missed it for long! Then I got used to some other controls, but "on screen buttons" used to be my favorite controls.
