### ISSUE TITLE
Can't link from gamejolt.net to a public profile created on Android

### ISSUE THREAD

**Issue by souliane** [MrStahlfelge/lightblocks#2]
Hi,

I am on the gamejolt.net instance and try to link to an already existing public profile that has been previously created on Android. I type my alias and the correct recovery email but it would not work and it says they are not matching. I checked in my google account settings and the recovery email that I typed is the good one.

I am not sure though if this is really a bug or maybe the dialog is only misleading - could you confirme that the expected information are the game's internal alias and the email is my google recovery one (the account has been created via google play store)?

Thx!

**Comment by MrStahlfelge** [comment]
The e-mail address is the one you set when you made your account on Android. Setting the recovery e-mail addeess is optional, so probably you did not set it. If you still have access to your account on Android, set the e-mail adress and you'll be able to link afterwards.

**Comment by souliane** [comment]
This works! Thank you :-)
