### ISSUE TITLE
Modern mode in local offline multiplayer

### ISSUE THREAD

**Issue by A7pr8** [MrStahlfelge/lightblocks#23]
It really annoys me that there is a modern mode for multiplayer in same device but not in local offline( for 2 devices using hotspot or same wifi)
Other than that there are no problems

**Comment by A7pr8** [comment]
Thanks for the quick response
If that is the case then goodluck and thank for that amazing game

**Comment by Yonle** [comment]
Is there a way to setup the server in Linux?

**Comment by MrStahlfelge** [comment]
Feature is present in new multiplayer mode that can be tested

**Comment by A7pr8** [comment]
It is hard to get that working
I figured a way to run it using termux but the new multiplayer tab is not showing on my other device and there is a delay in playing from the phone which is running the server so I don't think it is worth and I I don't It will work with hotspot bcz the tab disapper if I am connect to wifi
I wish u can add it to the regular local multiplay so it would be easier (for me atleast)
