### ISSUE TITLE
About classic mode's wall kick

### ISSUE THREAD

**Issue by SundayLee109** [MrStahlfelge/lightblocks#28]
I'm wondering whether classic mode has kick or not.
![Screenshot_20210406_211800](https://user-images.githubusercontent.com/82038537/113717216-fa0e0280-971d-11eb-8c07-bdb088214e8b.jpg)

![Screenshot_20210406_211805](https://user-images.githubusercontent.com/82038537/113717356-1e69df00-971e-11eb-8aee-a85f3256b2a5.jpg)

**Comment by MrStahlfelge** [comment]
There is no "real" classic guideline mode as it is for modern. Wall kicks were added by some games in the 90's as were some alternative rotation systems. There is a lot to read on this on the Hard Drop wiki.
