### ISSUE TITLE
"Rematch" button is missing when no turn has been played

### ISSUE THREAD

**Issue by souliane** [MrStahlfelge/lightblocks#3]
This is more a change request than a bug report: in multiplayer, when no turn has been played and the time is up, there is no "Rematch" button. It would be handy to have it, otherwise you have to scroll down to find another match against that person or search for her/his by typing the pseudonym (and I have a friend that has a crazy pseudonym that looks like a WIFI password...).

Thank you for your work!

**Comment by MrStahlfelge** [comment]
Thanks for the suggestion. You are right, this is an annoyance I also encountered before.

**Comment by MrStahlfelge** [comment]
Changed for the next version. I am not sure why there was a check if turns were played. 

The only explanation I can come up with is that I wanted to prevent that a person declining a match is hassled with repeating challenge retries. However, if that's the case, the other person should just ignore the challenges. So I hope there was no other reasn I forgot.
