### ISSUE TITLE
fingerprint scanner detected as controller on Google Pixel 4a 5G

### ISSUE THREAD

**Issue by hyperair** [MrStahlfelge/lightblocks#31]
On the Google Pixel 4a 5G, the fingerprint scanner is detected as a controller called `uinput-fpc`.

**Comment by MrStahlfelge** [comment]
Can confirm, I'll look into it

**Comment by hyperair** [comment]
Thanks. By the way, I couldn't assign keybindings for my bluetooth keyboard either, but I'm not sure whether that's related, or if I should file a new issue for it.

**Comment by MrStahlfelge** [comment]
> By the way, I couldn't assign keybindings for my bluetooth keyboard either, but I'm not sure whether that's related, or if I should file a new issue for it.

Is the keyboard reported as a game controller as well?

**Comment by hyperair** [comment]
It isn't, but Falling Lightblocks responds to some keys

**Comment by MrStahlfelge** [comment]
> It isn't, but Falling Lightblocks responds to some keys

Sorry not to come back to this second issue earlier, I forgot that there was a second point here. Yes, file a new issue for it describing what keys work and what not, thanks!
