### ISSUE TITLE
T-Spin Support if Possible

### ISSUE THREAD

**Issue by Yonle** [MrStahlfelge/lightblocks#33]
Tried to do T-Spin on this app but no luck. Would be cool of T-Spin support added

**Comment by MrStahlfelge** [comment]
T-Spin is possible, but it is hard to time in classic modes. You'll find it easier in the modern modes. 

BTW, T-Spin triple is supported as well.

**Comment by Yonle** [comment]
Oh i see, That's why i tried on classic mode it does not work. Gonna try it rn

**Comment by Yonle** [comment]
Ah yes. Tried T-Spin in Modern Mode. It works well. Time to close this issue
