### ISSUE TITLE
[BETA Multiplayer] Focus on our device-game move, do not sync our moves from server

### ISSUE THREAD

**Issue by Yonle** [MrStahlfelge/lightblocks#34]
When syncing our game moves from server to client, It would be slow for medium+ping user because we can't play with our speed anymore. So how about make the server broadcast our game moves while we're focusing our game speed?

__( Well, Sorry for some english mistake lol )__

**Comment by MrStahlfelge** [comment]
What is your ping? I found that a ping of up to 50ms is acceptable to play with

**Comment by Yonle** [comment]
Atleast 200 MS+, Which is slow. In fact it would better to not sync player move from server.

**Comment by MrStahlfelge** [comment]
Syncing the movements to the player is the new feature. This prevents frauds and gives new opportunities how the server can control the whole game. 
The downside is that this needs a fast connection to the server, faster than 50 ms. If you want to play with a friend of yours, best is to set up an own server locally as described here: https://github.com/MrStahlfelge/lightblocks/discussions/26

It's more easy than you think! :)
