### ISSUE TITLE
Increase responsive area of virtual D pad

### ISSUE THREAD

**Issue by dentistformyeye** [MrStahlfelge/lightblocks#36]
I prefer playing with the in-app D pad and often find that my taps fail to register because I accidentally tap too close to the center.
I'd like the area corresponding to each direction to increase so that tapping on an edge of the D pad or tapping close to the center will move the current lightblock.

**Comment by MrStahlfelge** [comment]
How often does it happen relative to overall taps? Asking to get a feeling how much the dead zone need to be smaller.

Did you check the settings to resize the d-pad? Does that help for you?

**Comment by dentistformyeye** [comment]
When my stack is high; i.e. when my taps become less precise b/c of stress, I'd say I tap an unresponsive area with at least one block per seven bag. It makes DASing very risky, so I resort to tapping as quickly as I can to get pieces near a wall.

Resizing the D-pad to make the center dead zone smaller increases the risk of tapping too close to the area near the D-pad's outline, which also doesn't register taps currently. The problem isn't so much that the dead zone is too big, but the responsive area of each individual D-pad button is too small in all directions.

**Comment by MrStahlfelge** [comment]
I agree, dead zone is too big for the d-pad. It is lowered for the next version. If you check it when the new version is released and you still have problems, please reopen.
