### ISSUE TITLE
Unable to change keybindings for bluetooth keyboard

### ISSUE THREAD

**Issue by hyperair** [MrStahlfelge/lightblocks#38]
When connecting a bluetooth keyboard to my phone, Falling Lightblocks recognizes the keyboard, but it doesn't show up in the controller config UI, and as a result, I can't change the keybindings.

Through some experimentation, I've found that the following keys work:
 - left/right to move pieces left and right
 - down for soft drop
 - up for hard drop
 - space for rotate

I'd like to set `up` for rotation and `space` for hard drop, but I'm unable to do that anywhere

**Comment by MrStahlfelge** [comment]
A hardware keyboard won't show up in the controller configuration as it is no game controller. A third pager in the settings screen appears when the system reports a hardware keyboard, where you can change the key binding.

**Comment by MrStahlfelge** [comment]
Does that help? If it is the case that you missed the keyboard settings page, maybe others did as well and we should add a hint in the gamepad config.

**Comment by hyperair** [comment]
Nice, thanks. That worked for everything except binding `space` to hard drop -- the config appears to alllow it, but nothing happens when I hit the space bar

**Comment by MrStahlfelge** [comment]
On which platform? Android?

**Comment by hyperair** [comment]
Yep

**Comment by MrStahlfelge** [comment]
Ah, interesting. I'll check it, thanks for the clarification!

**Comment by MrStahlfelge** [comment]
Hard drop problem is a possible dublicate with #39 

This issue remains open to add the keyboard configuration hint to the gamepad dialog.
