### ISSUE TITLE
A weird thing on web version

### ISSUE THREAD

**Issue by SundayLee109** [MrStahlfelge/lightblocks#42]
It shows me gravity control challenge when I using web version
![image](https://user-images.githubusercontent.com/82038537/125554367-dd388eaf-9bbd-450d-ac23-a0af52eedcd3.png)

**Comment by MrStahlfelge** [comment]
Checked the implementation. It is not wrong, it checks if your device reports to have an accelerometer.
Check this website, does it work for you? https://intel.github.io/generic-sensor-demos/orientation-phone/

**Comment by SundayLee109** [comment]
no

**Comment by SundayLee109** [comment]
It only happened for sometime
or maybe because of I let my chromebook to Tablet mode and change back to notebook mode

**Comment by MrStahlfelge** [comment]
Yes, probably tablet mode when you started the game! Closing this then.

**Comment by SundayLee109** [comment]
umm

**Comment by SundayLee109** [comment]
I test that and still not work
