### ISSUE TITLE
Connection problem on MacOS

### ISSUE THREAD

**Issue by rhodeon** [MrStahlfelge/lightblocks#46]
When trying to link an existing profile or set a new nickname on the desktop build on MacOS, I keep getting a connection error dialog.
I'm sure my internet connection is active because I'm able to connect to the public servers.

**Comment by MrStahlfelge** [comment]
For your own builds, you need to implement an own backend and client connection as this part of the app is not open sourced. Hence the connection error.
See https://github.com/MrStahlfelge/lightblocks/blob/848ed974d2e436350f793333347f3872e41594f1/core/src/de/golfgl/lightblocks/backend/BackendClient.java#L23

**Comment by rhodeon** [comment]
Oh, I see. 
Is there be a way to connect to an existing account (on Android) with a custom backend implementation?

**Comment by MrStahlfelge** [comment]
No - but you can add own accounts on your own backend.

**Comment by rhodeon** [comment]
Alright. Thanks.
