### ISSUE TITLE
Leaderboard player strength: Mode to show player centered

### ISSUE THREAD

**Issue by MrStahlfelge** [MrStahlfelge/lightblocks#8]
Leaderboard for turn based battle mode shows the players with the highest strength. For users with a Lightblocks account, it should be possible to switch to a player centered view, so other players of similar strength can be seen and challenged.

**Comment by souliane** [comment]
Really like this idea :-1:

**Comment by MrStahlfelge** [comment]
Backend work is done, [request example](https://lightblocks-backend.golfgl.de/v1/matches/similarStrengthPlayers/c471cb6a-e174-4a3d-bcaa-e6cdc869f83e)
